version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONBUFFERED=1
    command: python bot.py
    volumes:
      - .:/app